### ISSUE TITLE
Bug: Missing image for record button

### ISSUE THREAD

**Issue by kianlin** [Orbital-Mulgo/Project#24]
# Bug Report

Bug: Missing image for record button

## Description

In the path `frontend/static/images` is missing "recordbutton.png" file which is necessary for displaying at the dashboard.

### Steps to Reproduce

1. Upload the recordbutton.png image

### Expected Result

The expected result is to have the record button shown on the dashboard.

### Actual Results

The actual result currently is not showing the record button.

![image](https://user-images.githubusercontent.com/65789711/122189467-86c60100-cec3-11eb-9b1f-6ed6846f34f0.png)

**Comment by marvinljw** [comment]
Hi, have added the recordbutton.png into the "feature-audio-recording" branch le. I am focusing on functionality first, design will do afterwards.

**Comment by kianlin** [comment]
Pull request #30 has fixed this bug.
